// Code generated by mockery. DO NOT EDIT.

package mock

import (
	entity "github.com/kirklin/boot-backend-go-clean/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockAuthenticator is an autogenerated mock type for the Authenticator type
type MockAuthenticator struct {
	mock.Mock
}

type MockAuthenticator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthenticator) EXPECT() *MockAuthenticator_Expecter {
	return &MockAuthenticator_Expecter{mock: &_m.Mock}
}

// BlacklistToken provides a mock function with given fields: token, duration
func (_m *MockAuthenticator) BlacklistToken(token string, duration time.Duration) {
	_m.Called(token, duration)
}

// MockAuthenticator_BlacklistToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlacklistToken'
type MockAuthenticator_BlacklistToken_Call struct {
	*mock.Call
}

// BlacklistToken is a helper method to define mock.On call
//   - token string
//   - duration time.Duration
func (_e *MockAuthenticator_Expecter) BlacklistToken(token interface{}, duration interface{}) *MockAuthenticator_BlacklistToken_Call {
	return &MockAuthenticator_BlacklistToken_Call{Call: _e.mock.On("BlacklistToken", token, duration)}
}

func (_c *MockAuthenticator_BlacklistToken_Call) Run(run func(token string, duration time.Duration)) *MockAuthenticator_BlacklistToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Duration))
	})
	return _c
}

func (_c *MockAuthenticator_BlacklistToken_Call) Return() *MockAuthenticator_BlacklistToken_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAuthenticator_BlacklistToken_Call) RunAndReturn(run func(string, time.Duration)) *MockAuthenticator_BlacklistToken_Call {
	_c.Run(run)
	return _c
}

// GenerateTokenPair provides a mock function with given fields: user
func (_m *MockAuthenticator) GenerateTokenPair(user *entity.User) (*entity.TokenPair, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTokenPair")
	}

	var r0 *entity.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.User) (*entity.TokenPair, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(*entity.User) *entity.TokenPair); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TokenPair)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthenticator_GenerateTokenPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTokenPair'
type MockAuthenticator_GenerateTokenPair_Call struct {
	*mock.Call
}

// GenerateTokenPair is a helper method to define mock.On call
//   - user *entity.User
func (_e *MockAuthenticator_Expecter) GenerateTokenPair(user interface{}) *MockAuthenticator_GenerateTokenPair_Call {
	return &MockAuthenticator_GenerateTokenPair_Call{Call: _e.mock.On("GenerateTokenPair", user)}
}

func (_c *MockAuthenticator_GenerateTokenPair_Call) Run(run func(user *entity.User)) *MockAuthenticator_GenerateTokenPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.User))
	})
	return _c
}

func (_c *MockAuthenticator_GenerateTokenPair_Call) Return(_a0 *entity.TokenPair, _a1 error) *MockAuthenticator_GenerateTokenPair_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthenticator_GenerateTokenPair_Call) RunAndReturn(run func(*entity.User) (*entity.TokenPair, error)) *MockAuthenticator_GenerateTokenPair_Call {
	_c.Call.Return(run)
	return _c
}

// IsTokenBlacklisted provides a mock function with given fields: token
func (_m *MockAuthenticator) IsTokenBlacklisted(token string) bool {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for IsTokenBlacklisted")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockAuthenticator_IsTokenBlacklisted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTokenBlacklisted'
type MockAuthenticator_IsTokenBlacklisted_Call struct {
	*mock.Call
}

// IsTokenBlacklisted is a helper method to define mock.On call
//   - token string
func (_e *MockAuthenticator_Expecter) IsTokenBlacklisted(token interface{}) *MockAuthenticator_IsTokenBlacklisted_Call {
	return &MockAuthenticator_IsTokenBlacklisted_Call{Call: _e.mock.On("IsTokenBlacklisted", token)}
}

func (_c *MockAuthenticator_IsTokenBlacklisted_Call) Run(run func(token string)) *MockAuthenticator_IsTokenBlacklisted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAuthenticator_IsTokenBlacklisted_Call) Return(_a0 bool) *MockAuthenticator_IsTokenBlacklisted_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthenticator_IsTokenBlacklisted_Call) RunAndReturn(run func(string) bool) *MockAuthenticator_IsTokenBlacklisted_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccessToken provides a mock function with given fields: tokenString
func (_m *MockAuthenticator) ValidateAccessToken(tokenString string) (*entity.AccessTokenClaims, *entity.StandardClaims, error) {
	ret := _m.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 *entity.AccessTokenClaims
	var r1 *entity.StandardClaims
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (*entity.AccessTokenClaims, *entity.StandardClaims, error)); ok {
		return rf(tokenString)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.AccessTokenClaims); ok {
		r0 = rf(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AccessTokenClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *entity.StandardClaims); ok {
		r1 = rf(tokenString)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entity.StandardClaims)
		}
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(tokenString)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAuthenticator_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type MockAuthenticator_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - tokenString string
func (_e *MockAuthenticator_Expecter) ValidateAccessToken(tokenString interface{}) *MockAuthenticator_ValidateAccessToken_Call {
	return &MockAuthenticator_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", tokenString)}
}

func (_c *MockAuthenticator_ValidateAccessToken_Call) Run(run func(tokenString string)) *MockAuthenticator_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAuthenticator_ValidateAccessToken_Call) Return(_a0 *entity.AccessTokenClaims, _a1 *entity.StandardClaims, _a2 error) *MockAuthenticator_ValidateAccessToken_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAuthenticator_ValidateAccessToken_Call) RunAndReturn(run func(string) (*entity.AccessTokenClaims, *entity.StandardClaims, error)) *MockAuthenticator_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRefreshToken provides a mock function with given fields: tokenString
func (_m *MockAuthenticator) ValidateRefreshToken(tokenString string) (*entity.RefreshTokenClaims, *entity.StandardClaims, error) {
	ret := _m.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRefreshToken")
	}

	var r0 *entity.RefreshTokenClaims
	var r1 *entity.StandardClaims
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (*entity.RefreshTokenClaims, *entity.StandardClaims, error)); ok {
		return rf(tokenString)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.RefreshTokenClaims); ok {
		r0 = rf(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RefreshTokenClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *entity.StandardClaims); ok {
		r1 = rf(tokenString)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entity.StandardClaims)
		}
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(tokenString)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAuthenticator_ValidateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRefreshToken'
type MockAuthenticator_ValidateRefreshToken_Call struct {
	*mock.Call
}

// ValidateRefreshToken is a helper method to define mock.On call
//   - tokenString string
func (_e *MockAuthenticator_Expecter) ValidateRefreshToken(tokenString interface{}) *MockAuthenticator_ValidateRefreshToken_Call {
	return &MockAuthenticator_ValidateRefreshToken_Call{Call: _e.mock.On("ValidateRefreshToken", tokenString)}
}

func (_c *MockAuthenticator_ValidateRefreshToken_Call) Run(run func(tokenString string)) *MockAuthenticator_ValidateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAuthenticator_ValidateRefreshToken_Call) Return(_a0 *entity.RefreshTokenClaims, _a1 *entity.StandardClaims, _a2 error) *MockAuthenticator_ValidateRefreshToken_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAuthenticator_ValidateRefreshToken_Call) RunAndReturn(run func(string) (*entity.RefreshTokenClaims, *entity.StandardClaims, error)) *MockAuthenticator_ValidateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthenticator creates a new instance of MockAuthenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthenticator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthenticator {
	mock := &MockAuthenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
