// Code generated by mockery. DO NOT EDIT.

package mock

import (
	gateway "github.com/kirklin/boot-backend-go-clean/internal/domain/gateway"
	mock "github.com/stretchr/testify/mock"
)

// MockGeoIPResolver is an autogenerated mock type for the GeoIPResolver type
type MockGeoIPResolver struct {
	mock.Mock
}

type MockGeoIPResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGeoIPResolver) EXPECT() *MockGeoIPResolver_Expecter {
	return &MockGeoIPResolver_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockGeoIPResolver) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGeoIPResolver_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockGeoIPResolver_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockGeoIPResolver_Expecter) Close() *MockGeoIPResolver_Close_Call {
	return &MockGeoIPResolver_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockGeoIPResolver_Close_Call) Run(run func()) *MockGeoIPResolver_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGeoIPResolver_Close_Call) Return(_a0 error) *MockGeoIPResolver_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGeoIPResolver_Close_Call) RunAndReturn(run func() error) *MockGeoIPResolver_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Resolve provides a mock function with given fields: ip
func (_m *MockGeoIPResolver) Resolve(ip string) gateway.GeoLocation {
	ret := _m.Called(ip)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 gateway.GeoLocation
	if rf, ok := ret.Get(0).(func(string) gateway.GeoLocation); ok {
		r0 = rf(ip)
	} else {
		r0 = ret.Get(0).(gateway.GeoLocation)
	}

	return r0
}

// MockGeoIPResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockGeoIPResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ip string
func (_e *MockGeoIPResolver_Expecter) Resolve(ip interface{}) *MockGeoIPResolver_Resolve_Call {
	return &MockGeoIPResolver_Resolve_Call{Call: _e.mock.On("Resolve", ip)}
}

func (_c *MockGeoIPResolver_Resolve_Call) Run(run func(ip string)) *MockGeoIPResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGeoIPResolver_Resolve_Call) Return(_a0 gateway.GeoLocation) *MockGeoIPResolver_Resolve_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGeoIPResolver_Resolve_Call) RunAndReturn(run func(string) gateway.GeoLocation) *MockGeoIPResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGeoIPResolver creates a new instance of MockGeoIPResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGeoIPResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGeoIPResolver {
	mock := &MockGeoIPResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
