// Code generated by mockery. DO NOT EDIT.

package mock

import (
	context "context"

	cache "github.com/kirklin/boot-backend-go-clean/pkg/cache"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockCache) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCache_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockCache_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockCache_Expecter) Close() *MockCache_Close_Call {
	return &MockCache_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockCache_Close_Call) Run(run func()) *MockCache_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCache_Close_Call) Return(_a0 error) *MockCache_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_Close_Call) RunAndReturn(run func() error) *MockCache_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, keys
func (_m *MockCache) Delete(ctx context.Context, keys ...string) error {
	_va := make([]interface{}, len(keys))
	for _i := range keys {
		_va[_i] = keys[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = rf(ctx, keys...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCache_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCache_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - keys ...string
func (_e *MockCache_Expecter) Delete(ctx interface{}, keys ...interface{}) *MockCache_Delete_Call {
	return &MockCache_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{ctx}, keys...)...)}
}

func (_c *MockCache_Delete_Call) Run(run func(ctx context.Context, keys ...string)) *MockCache_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockCache_Delete_Call) Return(_a0 error) *MockCache_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_Delete_Call) RunAndReturn(run func(context.Context, ...string) error) *MockCache_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, key
func (_m *MockCache) Exists(ctx context.Context, key string) (bool, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCache_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockCache_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCache_Expecter) Exists(ctx interface{}, key interface{}) *MockCache_Exists_Call {
	return &MockCache_Exists_Call{Call: _e.mock.On("Exists", ctx, key)}
}

func (_c *MockCache_Exists_Call) Run(run func(ctx context.Context, key string)) *MockCache_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCache_Exists_Call) Return(_a0 bool, _a1 error) *MockCache_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCache_Exists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockCache_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Expire provides a mock function with given fields: ctx, key, ttl
func (_m *MockCache) Expire(ctx context.Context, key string, ttl time.Duration) (bool, error) {
	ret := _m.Called(ctx, key, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Expire")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) (bool, error)); ok {
		return rf(ctx, key, ttl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) bool); ok {
		r0 = rf(ctx, key, ttl)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = rf(ctx, key, ttl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCache_Expire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Expire'
type MockCache_Expire_Call struct {
	*mock.Call
}

// Expire is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - ttl time.Duration
func (_e *MockCache_Expecter) Expire(ctx interface{}, key interface{}, ttl interface{}) *MockCache_Expire_Call {
	return &MockCache_Expire_Call{Call: _e.mock.On("Expire", ctx, key, ttl)}
}

func (_c *MockCache_Expire_Call) Run(run func(ctx context.Context, key string, ttl time.Duration)) *MockCache_Expire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockCache_Expire_Call) Return(_a0 bool, _a1 error) *MockCache_Expire_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCache_Expire_Call) RunAndReturn(run func(context.Context, string, time.Duration) (bool, error)) *MockCache_Expire_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key, dest
func (_m *MockCache) Get(ctx context.Context, key string, dest any) error {
	ret := _m.Called(ctx, key, dest)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = rf(ctx, key, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - dest any
func (_e *MockCache_Expecter) Get(ctx interface{}, key interface{}, dest interface{}) *MockCache_Get_Call {
	return &MockCache_Get_Call{Call: _e.mock.On("Get", ctx, key, dest)}
}

func (_c *MockCache_Get_Call) Run(run func(ctx context.Context, key string, dest any)) *MockCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(any))
	})
	return _c
}

func (_c *MockCache_Get_Call) Return(_a0 error) *MockCache_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_Get_Call) RunAndReturn(run func(context.Context, string, any) error) *MockCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetBatch provides a mock function with given fields: ctx, keys
func (_m *MockCache) GetBatch(ctx context.Context, keys []string) (map[string]cache.Entry, error) {
	ret := _m.Called(ctx, keys)

	if len(ret) == 0 {
		panic("no return value specified for GetBatch")
	}

	var r0 map[string]cache.Entry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (map[string]cache.Entry, error)); ok {
		return rf(ctx, keys)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) map[string]cache.Entry); ok {
		r0 = rf(ctx, keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]cache.Entry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, keys)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCache_GetBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBatch'
type MockCache_GetBatch_Call struct {
	*mock.Call
}

// GetBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []string
func (_e *MockCache_Expecter) GetBatch(ctx interface{}, keys interface{}) *MockCache_GetBatch_Call {
	return &MockCache_GetBatch_Call{Call: _e.mock.On("GetBatch", ctx, keys)}
}

func (_c *MockCache_GetBatch_Call) Run(run func(ctx context.Context, keys []string)) *MockCache_GetBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockCache_GetBatch_Call) Return(_a0 map[string]cache.Entry, _a1 error) *MockCache_GetBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCache_GetBatch_Call) RunAndReturn(run func(context.Context, []string) (map[string]cache.Entry, error)) *MockCache_GetBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrLoad provides a mock function with given fields: ctx, key, dest, ttl, load, opts
func (_m *MockCache) GetOrLoad(ctx context.Context, key string, dest any, ttl time.Duration, load cache.Loader, opts ...cache.LoadOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, key, dest, ttl, load)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetOrLoad")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, any, time.Duration, cache.Loader, ...cache.LoadOption) error); ok {
		r0 = rf(ctx, key, dest, ttl, load, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCache_GetOrLoad_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrLoad'
type MockCache_GetOrLoad_Call struct {
	*mock.Call
}

// GetOrLoad is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - dest any
//   - ttl time.Duration
//   - load cache.Loader
//   - opts ...cache.LoadOption
func (_e *MockCache_Expecter) GetOrLoad(ctx interface{}, key interface{}, dest interface{}, ttl interface{}, load interface{}, opts ...interface{}) *MockCache_GetOrLoad_Call {
	return &MockCache_GetOrLoad_Call{Call: _e.mock.On("GetOrLoad",
		append([]interface{}{ctx, key, dest, ttl, load}, opts...)...)}
}

func (_c *MockCache_GetOrLoad_Call) Run(run func(ctx context.Context, key string, dest any, ttl time.Duration, load cache.Loader, opts ...cache.LoadOption)) *MockCache_GetOrLoad_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]cache.LoadOption, len(args)-5)
		for i, a := range args[5:] {
			if a != nil {
				variadicArgs[i] = a.(cache.LoadOption)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(any), args[3].(time.Duration), args[4].(cache.Loader), variadicArgs...)
	})
	return _c
}

func (_c *MockCache_GetOrLoad_Call) Return(_a0 error) *MockCache_GetOrLoad_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_GetOrLoad_Call) RunAndReturn(run func(context.Context, string, any, time.Duration, cache.Loader, ...cache.LoadOption) error) *MockCache_GetOrLoad_Call {
	_c.Call.Return(run)
	return _c
}

// Increment provides a mock function with given fields: ctx, key, delta
func (_m *MockCache) Increment(ctx context.Context, key string, delta int64) (int64, error) {
	ret := _m.Called(ctx, key, delta)

	if len(ret) == 0 {
		panic("no return value specified for Increment")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) (int64, error)); ok {
		return rf(ctx, key, delta)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) int64); ok {
		r0 = rf(ctx, key, delta)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, key, delta)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCache_Increment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Increment'
type MockCache_Increment_Call struct {
	*mock.Call
}

// Increment is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - delta int64
func (_e *MockCache_Expecter) Increment(ctx interface{}, key interface{}, delta interface{}) *MockCache_Increment_Call {
	return &MockCache_Increment_Call{Call: _e.mock.On("Increment", ctx, key, delta)}
}

func (_c *MockCache_Increment_Call) Run(run func(ctx context.Context, key string, delta int64)) *MockCache_Increment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *MockCache_Increment_Call) Return(_a0 int64, _a1 error) *MockCache_Increment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCache_Increment_Call) RunAndReturn(run func(context.Context, string, int64) (int64, error)) *MockCache_Increment_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *MockCache) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCache_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockCache_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCache_Expecter) Ping(ctx interface{}) *MockCache_Ping_Call {
	return &MockCache_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockCache_Ping_Call) Run(run func(ctx context.Context)) *MockCache_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCache_Ping_Call) Return(_a0 error) *MockCache_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_Ping_Call) RunAndReturn(run func(context.Context) error) *MockCache_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, key, value, ttl
func (_m *MockCache) Set(ctx context.Context, key string, value any, ttl time.Duration) error {
	ret := _m.Called(ctx, key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, any, time.Duration) error); ok {
		r0 = rf(ctx, key, value, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value any
//   - ttl time.Duration
func (_e *MockCache_Expecter) Set(ctx interface{}, key interface{}, value interface{}, ttl interface{}) *MockCache_Set_Call {
	return &MockCache_Set_Call{Call: _e.mock.On("Set", ctx, key, value, ttl)}
}

func (_c *MockCache_Set_Call) Run(run func(ctx context.Context, key string, value any, ttl time.Duration)) *MockCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(any), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockCache_Set_Call) Return(_a0 error) *MockCache_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_Set_Call) RunAndReturn(run func(context.Context, string, any, time.Duration) error) *MockCache_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetBatch provides a mock function with given fields: ctx, values, ttl, opts
func (_m *MockCache) SetBatch(ctx context.Context, values map[string]any, ttl time.Duration, opts ...cache.LoadOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, values, ttl)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SetBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]any, time.Duration, ...cache.LoadOption) error); ok {
		r0 = rf(ctx, values, ttl, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCache_SetBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBatch'
type MockCache_SetBatch_Call struct {
	*mock.Call
}

// SetBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - values map[string]any
//   - ttl time.Duration
//   - opts ...cache.LoadOption
func (_e *MockCache_Expecter) SetBatch(ctx interface{}, values interface{}, ttl interface{}, opts ...interface{}) *MockCache_SetBatch_Call {
	return &MockCache_SetBatch_Call{Call: _e.mock.On("SetBatch",
		append([]interface{}{ctx, values, ttl}, opts...)...)}
}

func (_c *MockCache_SetBatch_Call) Run(run func(ctx context.Context, values map[string]any, ttl time.Duration, opts ...cache.LoadOption)) *MockCache_SetBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]cache.LoadOption, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(cache.LoadOption)
			}
		}
		run(args[0].(context.Context), args[1].(map[string]any), args[2].(time.Duration), variadicArgs...)
	})
	return _c
}

func (_c *MockCache_SetBatch_Call) Return(_a0 error) *MockCache_SetBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_SetBatch_Call) RunAndReturn(run func(context.Context, map[string]any, time.Duration, ...cache.LoadOption) error) *MockCache_SetBatch_Call {
	_c.Call.Return(run)
	return _c
}

// SetMissingBatch provides a mock function with given fields: ctx, keys, opts
func (_m *MockCache) SetMissingBatch(ctx context.Context, keys []string, opts ...cache.LoadOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, keys)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SetMissingBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, ...cache.LoadOption) error); ok {
		r0 = rf(ctx, keys, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCache_SetMissingBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMissingBatch'
type MockCache_SetMissingBatch_Call struct {
	*mock.Call
}

// SetMissingBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []string
//   - opts ...cache.LoadOption
func (_e *MockCache_Expecter) SetMissingBatch(ctx interface{}, keys interface{}, opts ...interface{}) *MockCache_SetMissingBatch_Call {
	return &MockCache_SetMissingBatch_Call{Call: _e.mock.On("SetMissingBatch",
		append([]interface{}{ctx, keys}, opts...)...)}
}

func (_c *MockCache_SetMissingBatch_Call) Run(run func(ctx context.Context, keys []string, opts ...cache.LoadOption)) *MockCache_SetMissingBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]cache.LoadOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(cache.LoadOption)
			}
		}
		run(args[0].(context.Context), args[1].([]string), variadicArgs...)
	})
	return _c
}

func (_c *MockCache_SetMissingBatch_Call) Return(_a0 error) *MockCache_SetMissingBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_SetMissingBatch_Call) RunAndReturn(run func(context.Context, []string, ...cache.LoadOption) error) *MockCache_SetMissingBatch_Call {
	_c.Call.Return(run)
	return _c
}

// SetNX provides a mock function with given fields: ctx, key, value, ttl
func (_m *MockCache) SetNX(ctx context.Context, key string, value any, ttl time.Duration) (bool, error) {
	ret := _m.Called(ctx, key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetNX")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, any, time.Duration) (bool, error)); ok {
		return rf(ctx, key, value, ttl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, any, time.Duration) bool); ok {
		r0 = rf(ctx, key, value, ttl)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, any, time.Duration) error); ok {
		r1 = rf(ctx, key, value, ttl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCache_SetNX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNX'
type MockCache_SetNX_Call struct {
	*mock.Call
}

// SetNX is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value any
//   - ttl time.Duration
func (_e *MockCache_Expecter) SetNX(ctx interface{}, key interface{}, value interface{}, ttl interface{}) *MockCache_SetNX_Call {
	return &MockCache_SetNX_Call{Call: _e.mock.On("SetNX", ctx, key, value, ttl)}
}

func (_c *MockCache_SetNX_Call) Run(run func(ctx context.Context, key string, value any, ttl time.Duration)) *MockCache_SetNX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(any), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockCache_SetNX_Call) Return(_a0 bool, _a1 error) *MockCache_SetNX_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCache_SetNX_Call) RunAndReturn(run func(context.Context, string, any, time.Duration) (bool, error)) *MockCache_SetNX_Call {
	_c.Call.Return(run)
	return _c
}

// Stats provides a mock function with no fields
func (_m *MockCache) Stats() cache.Stats {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 cache.Stats
	if rf, ok := ret.Get(0).(func() cache.Stats); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(cache.Stats)
	}

	return r0
}

// MockCache_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockCache_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
func (_e *MockCache_Expecter) Stats() *MockCache_Stats_Call {
	return &MockCache_Stats_Call{Call: _e.mock.On("Stats")}
}

func (_c *MockCache_Stats_Call) Run(run func()) *MockCache_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCache_Stats_Call) Return(_a0 cache.Stats) *MockCache_Stats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_Stats_Call) RunAndReturn(run func() cache.Stats) *MockCache_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// TTL provides a mock function with given fields: ctx, key
func (_m *MockCache) TTL(ctx context.Context, key string) (time.Duration, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for TTL")
	}

	var r0 time.Duration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (time.Duration, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) time.Duration); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCache_TTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TTL'
type MockCache_TTL_Call struct {
	*mock.Call
}

// TTL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCache_Expecter) TTL(ctx interface{}, key interface{}) *MockCache_TTL_Call {
	return &MockCache_TTL_Call{Call: _e.mock.On("TTL", ctx, key)}
}

func (_c *MockCache_TTL_Call) Run(run func(ctx context.Context, key string)) *MockCache_TTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCache_TTL_Call) Return(_a0 time.Duration, _a1 error) *MockCache_TTL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCache_TTL_Call) RunAndReturn(run func(context.Context, string) (time.Duration, error)) *MockCache_TTL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
