// Code generated by mockery. DO NOT EDIT.

package mock

import (
	context "context"
	io "io"

	iter "iter"

	mock "github.com/stretchr/testify/mock"

	storage "github.com/kirklin/boot-backend-go-clean/pkg/storage"

	time "time"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Copy provides a mock function with given fields: ctx, dstKey, srcKey
func (_m *MockStorage) Copy(ctx context.Context, dstKey string, srcKey string) error {
	ret := _m.Called(ctx, dstKey, srcKey)

	if len(ret) == 0 {
		panic("no return value specified for Copy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, dstKey, srcKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Copy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Copy'
type MockStorage_Copy_Call struct {
	*mock.Call
}

// Copy is a helper method to define mock.On call
//   - ctx context.Context
//   - dstKey string
//   - srcKey string
func (_e *MockStorage_Expecter) Copy(ctx interface{}, dstKey interface{}, srcKey interface{}) *MockStorage_Copy_Call {
	return &MockStorage_Copy_Call{Call: _e.mock.On("Copy", ctx, dstKey, srcKey)}
}

func (_c *MockStorage_Copy_Call) Run(run func(ctx context.Context, dstKey string, srcKey string)) *MockStorage_Copy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockStorage_Copy_Call) Return(_a0 error) *MockStorage_Copy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Copy_Call) RunAndReturn(run func(context.Context, string, string) error) *MockStorage_Copy_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, keys
func (_m *MockStorage) Delete(ctx context.Context, keys ...string) error {
	_va := make([]interface{}, len(keys))
	for _i := range keys {
		_va[_i] = keys[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = rf(ctx, keys...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - keys ...string
func (_e *MockStorage_Expecter) Delete(ctx interface{}, keys ...interface{}) *MockStorage_Delete_Call {
	return &MockStorage_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{ctx}, keys...)...)}
}

func (_c *MockStorage_Delete_Call) Run(run func(ctx context.Context, keys ...string)) *MockStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockStorage_Delete_Call) Return(_a0 error) *MockStorage_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Delete_Call) RunAndReturn(run func(context.Context, ...string) error) *MockStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, key
func (_m *MockStorage) Exists(ctx context.Context, key string) (bool, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockStorage_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStorage_Expecter) Exists(ctx interface{}, key interface{}) *MockStorage_Exists_Call {
	return &MockStorage_Exists_Call{Call: _e.mock.On("Exists", ctx, key)}
}

func (_c *MockStorage_Exists_Call) Run(run func(ctx context.Context, key string)) *MockStorage_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_Exists_Call) Return(_a0 bool, _a1 error) *MockStorage_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_Exists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockStorage_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key
func (_m *MockStorage) Get(ctx context.Context, key string) (io.ReadCloser, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStorage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStorage_Expecter) Get(ctx interface{}, key interface{}) *MockStorage_Get_Call {
	return &MockStorage_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockStorage_Get_Call) Run(run func(ctx context.Context, key string)) *MockStorage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_Get_Call) Return(_a0 io.ReadCloser, _a1 error) *MockStorage_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_Get_Call) RunAndReturn(run func(context.Context, string) (io.ReadCloser, error)) *MockStorage_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, prefix, opts
func (_m *MockStorage) List(ctx context.Context, prefix string, opts ...storage.ListOption) iter.Seq2[storage.ObjectInfo, error] {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, prefix)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 iter.Seq2[storage.ObjectInfo, error]
	if rf, ok := ret.Get(0).(func(context.Context, string, ...storage.ListOption) iter.Seq2[storage.ObjectInfo, error]); ok {
		r0 = rf(ctx, prefix, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq2[storage.ObjectInfo, error])
		}
	}

	return r0
}

// MockStorage_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockStorage_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
//   - opts ...storage.ListOption
func (_e *MockStorage_Expecter) List(ctx interface{}, prefix interface{}, opts ...interface{}) *MockStorage_List_Call {
	return &MockStorage_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx, prefix}, opts...)...)}
}

func (_c *MockStorage_List_Call) Run(run func(ctx context.Context, prefix string, opts ...storage.ListOption)) *MockStorage_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]storage.ListOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(storage.ListOption)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockStorage_List_Call) Return(_a0 iter.Seq2[storage.ObjectInfo, error]) *MockStorage_List_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_List_Call) RunAndReturn(run func(context.Context, string, ...storage.ListOption) iter.Seq2[storage.ObjectInfo, error]) *MockStorage_List_Call {
	_c.Call.Return(run)
	return _c
}

// Move provides a mock function with given fields: ctx, dstKey, srcKey
func (_m *MockStorage) Move(ctx context.Context, dstKey string, srcKey string) error {
	ret := _m.Called(ctx, dstKey, srcKey)

	if len(ret) == 0 {
		panic("no return value specified for Move")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, dstKey, srcKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Move_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Move'
type MockStorage_Move_Call struct {
	*mock.Call
}

// Move is a helper method to define mock.On call
//   - ctx context.Context
//   - dstKey string
//   - srcKey string
func (_e *MockStorage_Expecter) Move(ctx interface{}, dstKey interface{}, srcKey interface{}) *MockStorage_Move_Call {
	return &MockStorage_Move_Call{Call: _e.mock.On("Move", ctx, dstKey, srcKey)}
}

func (_c *MockStorage_Move_Call) Run(run func(ctx context.Context, dstKey string, srcKey string)) *MockStorage_Move_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockStorage_Move_Call) Return(_a0 error) *MockStorage_Move_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Move_Call) RunAndReturn(run func(context.Context, string, string) error) *MockStorage_Move_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *MockStorage) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockStorage_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorage_Expecter) Ping(ctx interface{}) *MockStorage_Ping_Call {
	return &MockStorage_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockStorage_Ping_Call) Run(run func(ctx context.Context)) *MockStorage_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStorage_Ping_Call) Return(_a0 error) *MockStorage_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Ping_Call) RunAndReturn(run func(context.Context) error) *MockStorage_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// PresignGet provides a mock function with given fields: ctx, key, expiry, opts
func (_m *MockStorage) PresignGet(ctx context.Context, key string, expiry time.Duration, opts ...storage.PresignGetOption) (string, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, key, expiry)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PresignGet")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration, ...storage.PresignGetOption) (string, error)); ok {
		return rf(ctx, key, expiry, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration, ...storage.PresignGetOption) string); ok {
		r0 = rf(ctx, key, expiry, opts...)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration, ...storage.PresignGetOption) error); ok {
		r1 = rf(ctx, key, expiry, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_PresignGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignGet'
type MockStorage_PresignGet_Call struct {
	*mock.Call
}

// PresignGet is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - expiry time.Duration
//   - opts ...storage.PresignGetOption
func (_e *MockStorage_Expecter) PresignGet(ctx interface{}, key interface{}, expiry interface{}, opts ...interface{}) *MockStorage_PresignGet_Call {
	return &MockStorage_PresignGet_Call{Call: _e.mock.On("PresignGet",
		append([]interface{}{ctx, key, expiry}, opts...)...)}
}

func (_c *MockStorage_PresignGet_Call) Run(run func(ctx context.Context, key string, expiry time.Duration, opts ...storage.PresignGetOption)) *MockStorage_PresignGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]storage.PresignGetOption, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(storage.PresignGetOption)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration), variadicArgs...)
	})
	return _c
}

func (_c *MockStorage_PresignGet_Call) Return(_a0 string, _a1 error) *MockStorage_PresignGet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_PresignGet_Call) RunAndReturn(run func(context.Context, string, time.Duration, ...storage.PresignGetOption) (string, error)) *MockStorage_PresignGet_Call {
	_c.Call.Return(run)
	return _c
}

// PresignPost provides a mock function with given fields: ctx, key, expiry, opts
func (_m *MockStorage) PresignPost(ctx context.Context, key string, expiry time.Duration, opts ...storage.PresignPostOption) (storage.PostUpload, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, key, expiry)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PresignPost")
	}

	var r0 storage.PostUpload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration, ...storage.PresignPostOption) (storage.PostUpload, error)); ok {
		return rf(ctx, key, expiry, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration, ...storage.PresignPostOption) storage.PostUpload); ok {
		r0 = rf(ctx, key, expiry, opts...)
	} else {
		r0 = ret.Get(0).(storage.PostUpload)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration, ...storage.PresignPostOption) error); ok {
		r1 = rf(ctx, key, expiry, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_PresignPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignPost'
type MockStorage_PresignPost_Call struct {
	*mock.Call
}

// PresignPost is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - expiry time.Duration
//   - opts ...storage.PresignPostOption
func (_e *MockStorage_Expecter) PresignPost(ctx interface{}, key interface{}, expiry interface{}, opts ...interface{}) *MockStorage_PresignPost_Call {
	return &MockStorage_PresignPost_Call{Call: _e.mock.On("PresignPost",
		append([]interface{}{ctx, key, expiry}, opts...)...)}
}

func (_c *MockStorage_PresignPost_Call) Run(run func(ctx context.Context, key string, expiry time.Duration, opts ...storage.PresignPostOption)) *MockStorage_PresignPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]storage.PresignPostOption, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(storage.PresignPostOption)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration), variadicArgs...)
	})
	return _c
}

func (_c *MockStorage_PresignPost_Call) Return(_a0 storage.PostUpload, _a1 error) *MockStorage_PresignPost_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_PresignPost_Call) RunAndReturn(run func(context.Context, string, time.Duration, ...storage.PresignPostOption) (storage.PostUpload, error)) *MockStorage_PresignPost_Call {
	_c.Call.Return(run)
	return _c
}

// PresignPut provides a mock function with given fields: ctx, key, expiry, opts
func (_m *MockStorage) PresignPut(ctx context.Context, key string, expiry time.Duration, opts ...storage.PresignPutOption) (string, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, key, expiry)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PresignPut")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration, ...storage.PresignPutOption) (string, error)); ok {
		return rf(ctx, key, expiry, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration, ...storage.PresignPutOption) string); ok {
		r0 = rf(ctx, key, expiry, opts...)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration, ...storage.PresignPutOption) error); ok {
		r1 = rf(ctx, key, expiry, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_PresignPut_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignPut'
type MockStorage_PresignPut_Call struct {
	*mock.Call
}

// PresignPut is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - expiry time.Duration
//   - opts ...storage.PresignPutOption
func (_e *MockStorage_Expecter) PresignPut(ctx interface{}, key interface{}, expiry interface{}, opts ...interface{}) *MockStorage_PresignPut_Call {
	return &MockStorage_PresignPut_Call{Call: _e.mock.On("PresignPut",
		append([]interface{}{ctx, key, expiry}, opts...)...)}
}

func (_c *MockStorage_PresignPut_Call) Run(run func(ctx context.Context, key string, expiry time.Duration, opts ...storage.PresignPutOption)) *MockStorage_PresignPut_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]storage.PresignPutOption, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(storage.PresignPutOption)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration), variadicArgs...)
	})
	return _c
}

func (_c *MockStorage_PresignPut_Call) Return(_a0 string, _a1 error) *MockStorage_PresignPut_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_PresignPut_Call) RunAndReturn(run func(context.Context, string, time.Duration, ...storage.PresignPutOption) (string, error)) *MockStorage_PresignPut_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: ctx, key, r, size, opts
func (_m *MockStorage) Put(ctx context.Context, key string, r io.Reader, size int64, opts ...storage.PutOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, key, r, size)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64, ...storage.PutOption) error); ok {
		r0 = rf(ctx, key, r, size, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockStorage_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - r io.Reader
//   - size int64
//   - opts ...storage.PutOption
func (_e *MockStorage_Expecter) Put(ctx interface{}, key interface{}, r interface{}, size interface{}, opts ...interface{}) *MockStorage_Put_Call {
	return &MockStorage_Put_Call{Call: _e.mock.On("Put",
		append([]interface{}{ctx, key, r, size}, opts...)...)}
}

func (_c *MockStorage_Put_Call) Run(run func(ctx context.Context, key string, r io.Reader, size int64, opts ...storage.PutOption)) *MockStorage_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]storage.PutOption, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(storage.PutOption)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader), args[3].(int64), variadicArgs...)
	})
	return _c
}

func (_c *MockStorage_Put_Call) Return(_a0 error) *MockStorage_Put_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Put_Call) RunAndReturn(run func(context.Context, string, io.Reader, int64, ...storage.PutOption) error) *MockStorage_Put_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function with given fields: ctx, key
func (_m *MockStorage) Stat(ctx context.Context, key string) (storage.ObjectInfo, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 storage.ObjectInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (storage.ObjectInfo, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) storage.ObjectInfo); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(storage.ObjectInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockStorage_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStorage_Expecter) Stat(ctx interface{}, key interface{}) *MockStorage_Stat_Call {
	return &MockStorage_Stat_Call{Call: _e.mock.On("Stat", ctx, key)}
}

func (_c *MockStorage_Stat_Call) Run(run func(ctx context.Context, key string)) *MockStorage_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_Stat_Call) Return(_a0 storage.ObjectInfo, _a1 error) *MockStorage_Stat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_Stat_Call) RunAndReturn(run func(context.Context, string) (storage.ObjectInfo, error)) *MockStorage_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
