// Code generated by mockery. DO NOT EDIT.

package mock

import (
	context "context"

	entity "github.com/kirklin/boot-backend-go-clean/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockAuthUseCase is an autogenerated mock type for the AuthUseCase type
type MockAuthUseCase struct {
	mock.Mock
}

type MockAuthUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthUseCase) EXPECT() *MockAuthUseCase_Expecter {
	return &MockAuthUseCase_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, req
func (_m *MockAuthUseCase) Login(ctx context.Context, req *entity.LoginRequest) (*entity.LoginResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *entity.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.LoginRequest) (*entity.LoginResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.LoginRequest) *entity.LoginResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.LoginRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthUseCase_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthUseCase_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entity.LoginRequest
func (_e *MockAuthUseCase_Expecter) Login(ctx interface{}, req interface{}) *MockAuthUseCase_Login_Call {
	return &MockAuthUseCase_Login_Call{Call: _e.mock.On("Login", ctx, req)}
}

func (_c *MockAuthUseCase_Login_Call) Run(run func(ctx context.Context, req *entity.LoginRequest)) *MockAuthUseCase_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.LoginRequest))
	})
	return _c
}

func (_c *MockAuthUseCase_Login_Call) Return(_a0 *entity.LoginResponse, _a1 error) *MockAuthUseCase_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthUseCase_Login_Call) RunAndReturn(run func(context.Context, *entity.LoginRequest) (*entity.LoginResponse, error)) *MockAuthUseCase_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, req
func (_m *MockAuthUseCase) Logout(ctx context.Context, req *entity.LogoutRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.LogoutRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthUseCase_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthUseCase_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entity.LogoutRequest
func (_e *MockAuthUseCase_Expecter) Logout(ctx interface{}, req interface{}) *MockAuthUseCase_Logout_Call {
	return &MockAuthUseCase_Logout_Call{Call: _e.mock.On("Logout", ctx, req)}
}

func (_c *MockAuthUseCase_Logout_Call) Run(run func(ctx context.Context, req *entity.LogoutRequest)) *MockAuthUseCase_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.LogoutRequest))
	})
	return _c
}

func (_c *MockAuthUseCase_Logout_Call) Return(_a0 error) *MockAuthUseCase_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthUseCase_Logout_Call) RunAndReturn(run func(context.Context, *entity.LogoutRequest) error) *MockAuthUseCase_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function with given fields: ctx, req
func (_m *MockAuthUseCase) RefreshToken(ctx context.Context, req *entity.RefreshTokenRequest) (*entity.RefreshTokenResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *entity.RefreshTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.RefreshTokenRequest) (*entity.RefreshTokenResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.RefreshTokenRequest) *entity.RefreshTokenResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RefreshTokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.RefreshTokenRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthUseCase_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockAuthUseCase_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entity.RefreshTokenRequest
func (_e *MockAuthUseCase_Expecter) RefreshToken(ctx interface{}, req interface{}) *MockAuthUseCase_RefreshToken_Call {
	return &MockAuthUseCase_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, req)}
}

func (_c *MockAuthUseCase_RefreshToken_Call) Run(run func(ctx context.Context, req *entity.RefreshTokenRequest)) *MockAuthUseCase_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.RefreshTokenRequest))
	})
	return _c
}

func (_c *MockAuthUseCase_RefreshToken_Call) Return(_a0 *entity.RefreshTokenResponse, _a1 error) *MockAuthUseCase_RefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthUseCase_RefreshToken_Call) RunAndReturn(run func(context.Context, *entity.RefreshTokenRequest) (*entity.RefreshTokenResponse, error)) *MockAuthUseCase_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, req
func (_m *MockAuthUseCase) Register(ctx context.Context, req *entity.RegisterRequest) (*entity.RegisterResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *entity.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.RegisterRequest) (*entity.RegisterResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.RegisterRequest) *entity.RegisterResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.RegisterRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthUseCase_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthUseCase_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entity.RegisterRequest
func (_e *MockAuthUseCase_Expecter) Register(ctx interface{}, req interface{}) *MockAuthUseCase_Register_Call {
	return &MockAuthUseCase_Register_Call{Call: _e.mock.On("Register", ctx, req)}
}

func (_c *MockAuthUseCase_Register_Call) Run(run func(ctx context.Context, req *entity.RegisterRequest)) *MockAuthUseCase_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.RegisterRequest))
	})
	return _c
}

func (_c *MockAuthUseCase_Register_Call) Return(_a0 *entity.RegisterResponse, _a1 error) *MockAuthUseCase_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthUseCase_Register_Call) RunAndReturn(run func(context.Context, *entity.RegisterRequest) (*entity.RegisterResponse, error)) *MockAuthUseCase_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthUseCase creates a new instance of MockAuthUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthUseCase {
	mock := &MockAuthUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
