// Code generated by mockery. DO NOT EDIT.

package mock

import (
	context "context"

	entity "github.com/kirklin/boot-backend-go-clean/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockLoginActivityRepository is an autogenerated mock type for the LoginActivityRepository type
type MockLoginActivityRepository struct {
	mock.Mock
}

type MockLoginActivityRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoginActivityRepository) EXPECT() *MockLoginActivityRepository_Expecter {
	return &MockLoginActivityRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, activity
func (_m *MockLoginActivityRepository) Create(ctx context.Context, activity *entity.LoginActivity) error {
	ret := _m.Called(ctx, activity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.LoginActivity) error); ok {
		r0 = rf(ctx, activity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLoginActivityRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockLoginActivityRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - activity *entity.LoginActivity
func (_e *MockLoginActivityRepository_Expecter) Create(ctx interface{}, activity interface{}) *MockLoginActivityRepository_Create_Call {
	return &MockLoginActivityRepository_Create_Call{Call: _e.mock.On("Create", ctx, activity)}
}

func (_c *MockLoginActivityRepository_Create_Call) Run(run func(ctx context.Context, activity *entity.LoginActivity)) *MockLoginActivityRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.LoginActivity))
	})
	return _c
}

func (_c *MockLoginActivityRepository_Create_Call) Return(_a0 error) *MockLoginActivityRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoginActivityRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.LoginActivity) error) *MockLoginActivityRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBefore provides a mock function with given fields: ctx, before
func (_m *MockLoginActivityRepository) DeleteBefore(ctx context.Context, before time.Time) (int64, error) {
	ret := _m.Called(ctx, before)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBefore")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return rf(ctx, before)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = rf(ctx, before)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, before)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoginActivityRepository_DeleteBefore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBefore'
type MockLoginActivityRepository_DeleteBefore_Call struct {
	*mock.Call
}

// DeleteBefore is a helper method to define mock.On call
//   - ctx context.Context
//   - before time.Time
func (_e *MockLoginActivityRepository_Expecter) DeleteBefore(ctx interface{}, before interface{}) *MockLoginActivityRepository_DeleteBefore_Call {
	return &MockLoginActivityRepository_DeleteBefore_Call{Call: _e.mock.On("DeleteBefore", ctx, before)}
}

func (_c *MockLoginActivityRepository_DeleteBefore_Call) Run(run func(ctx context.Context, before time.Time)) *MockLoginActivityRepository_DeleteBefore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockLoginActivityRepository_DeleteBefore_Call) Return(_a0 int64, _a1 error) *MockLoginActivityRepository_DeleteBefore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoginActivityRepository_DeleteBefore_Call) RunAndReturn(run func(context.Context, time.Time) (int64, error)) *MockLoginActivityRepository_DeleteBefore_Call {
	_c.Call.Return(run)
	return _c
}

// FindLatestByUserID provides a mock function with given fields: ctx, userID
func (_m *MockLoginActivityRepository) FindLatestByUserID(ctx context.Context, userID int64) (*entity.LoginActivity, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindLatestByUserID")
	}

	var r0 *entity.LoginActivity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.LoginActivity, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.LoginActivity); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.LoginActivity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoginActivityRepository_FindLatestByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindLatestByUserID'
type MockLoginActivityRepository_FindLatestByUserID_Call struct {
	*mock.Call
}

// FindLatestByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockLoginActivityRepository_Expecter) FindLatestByUserID(ctx interface{}, userID interface{}) *MockLoginActivityRepository_FindLatestByUserID_Call {
	return &MockLoginActivityRepository_FindLatestByUserID_Call{Call: _e.mock.On("FindLatestByUserID", ctx, userID)}
}

func (_c *MockLoginActivityRepository_FindLatestByUserID_Call) Run(run func(ctx context.Context, userID int64)) *MockLoginActivityRepository_FindLatestByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockLoginActivityRepository_FindLatestByUserID_Call) Return(_a0 *entity.LoginActivity, _a1 error) *MockLoginActivityRepository_FindLatestByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoginActivityRepository_FindLatestByUserID_Call) RunAndReturn(run func(context.Context, int64) (*entity.LoginActivity, error)) *MockLoginActivityRepository_FindLatestByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoginActivityRepository creates a new instance of MockLoginActivityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoginActivityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoginActivityRepository {
	mock := &MockLoginActivityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
