// Code generated by mockery. DO NOT EDIT.

package mock

import (
	context "context"

	entity "github.com/kirklin/boot-backend-go-clean/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockUserUseCase is an autogenerated mock type for the UserUseCase type
type MockUserUseCase struct {
	mock.Mock
}

type MockUserUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserUseCase) EXPECT() *MockUserUseCase_Expecter {
	return &MockUserUseCase_Expecter{mock: &_m.Mock}
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *MockUserUseCase) GetUserByID(ctx context.Context, id int64) (*entity.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserUseCase_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserUseCase_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockUserUseCase_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockUserUseCase_GetUserByID_Call {
	return &MockUserUseCase_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockUserUseCase_GetUserByID_Call) Run(run func(ctx context.Context, id int64)) *MockUserUseCase_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockUserUseCase_GetUserByID_Call) Return(_a0 *entity.User, _a1 error) *MockUserUseCase_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserUseCase_GetUserByID_Call) RunAndReturn(run func(context.Context, int64) (*entity.User, error)) *MockUserUseCase_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteUser provides a mock function with given fields: ctx, id
func (_m *MockUserUseCase) SoftDeleteUser(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserUseCase_SoftDeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteUser'
type MockUserUseCase_SoftDeleteUser_Call struct {
	*mock.Call
}

// SoftDeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockUserUseCase_Expecter) SoftDeleteUser(ctx interface{}, id interface{}) *MockUserUseCase_SoftDeleteUser_Call {
	return &MockUserUseCase_SoftDeleteUser_Call{Call: _e.mock.On("SoftDeleteUser", ctx, id)}
}

func (_c *MockUserUseCase_SoftDeleteUser_Call) Run(run func(ctx context.Context, id int64)) *MockUserUseCase_SoftDeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockUserUseCase_SoftDeleteUser_Call) Return(_a0 error) *MockUserUseCase_SoftDeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserUseCase_SoftDeleteUser_Call) RunAndReturn(run func(context.Context, int64) error) *MockUserUseCase_SoftDeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx, user
func (_m *MockUserUseCase) UpdateUser(ctx context.Context, user *entity.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserUseCase_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUserUseCase_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entity.User
func (_e *MockUserUseCase_Expecter) UpdateUser(ctx interface{}, user interface{}) *MockUserUseCase_UpdateUser_Call {
	return &MockUserUseCase_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, user)}
}

func (_c *MockUserUseCase_UpdateUser_Call) Run(run func(ctx context.Context, user *entity.User)) *MockUserUseCase_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.User))
	})
	return _c
}

func (_c *MockUserUseCase_UpdateUser_Call) Return(_a0 error) *MockUserUseCase_UpdateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserUseCase_UpdateUser_Call) RunAndReturn(run func(context.Context, *entity.User) error) *MockUserUseCase_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserUseCase creates a new instance of MockUserUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserUseCase {
	mock := &MockUserUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
