{
 "title": "Boot Backend Services",
 "tags": [
  "go",
  "gin"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Total QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "P99 Latency (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "P99 Latency"
    }
   ]
  },
  {
   "title": "Go Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "Goroutines" }
   ]
  }
 ]
}